"""0004_init_flow_app

Revision ID: 0717870cbe0b
Revises: 8d884983367d
Create Date: 2026-03-21 21:26:06.699763

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0717870cbe0b'
down_revision: Union[str, Sequence[str], None] = '8d884983367d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'candidates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'specialty',
            sa.Enum('BE', 'FE', 'QA', 'MOB', 'DEVOPS', name='flow_candidate_specialty'),
            nullable=False,
        ),
        sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'candidate_ways',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column(
            'period_start',
            sa.Date(),
            server_default=sa.text('CURRENT_DATE'),
            nullable=False,
        ),
        sa.Column('period_end', sa.Date(), nullable=True),
        sa.Column(
            'specialty',
            sa.Enum('BE', 'FE', 'QA', 'MOB', 'DEVOPS', name='flow_way_specialty'),
            nullable=False,
        ),
        sa.Column(
            'decision',
            sa.Enum('HIRED', 'REJECTED', 'IN_PROGRESS', 'ON_HOLD', name='flow_way_decision'),
            server_default='IN_PROGRESS',
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='flow_way_status'),
            server_default='ACTIVE',
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'candidate_way_sections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('way_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'type',
            sa.Enum('HR', 'TECH', 'SD', 'TEAM', name='flow_way_section_type'),
            server_default='HR',
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'NEW',
                'IN_PROGRESS',
                'END',
                name='flow_way_section_status',
            ),
            server_default='NEW',
            nullable=False,
        ),
        sa.Column('review', sa.Text(), nullable=True),
        sa.Column(
            'decision',
            sa.Enum('REFUSE', 'RECOMMENDED', 'PENDING', name='flow_way_section_decision'),
            server_default='PENDING',
            nullable=False,
        ),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('skill_assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(['way_id'], ['candidate_ways.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'candidate_way_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('way_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['way_id'], ['candidate_ways.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('way_id', 'tag_id', name='uq_candidate_way_tag'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_way_tags')
    op.drop_table('candidate_way_sections')
    op.drop_table('candidate_ways')
    op.drop_table('tags')
    op.drop_table('candidates')
    # Удаляем enum-типы — они не удаляются автоматически
    op.execute('DROP TYPE IF EXISTS flow_way_section_decision')
    op.execute('DROP TYPE IF EXISTS flow_way_section_status')
    op.execute('DROP TYPE IF EXISTS flow_way_section_type')
    op.execute('DROP TYPE IF EXISTS flow_way_decision')
    op.execute('DROP TYPE IF EXISTS flow_way_status')
    op.execute('DROP TYPE IF EXISTS flow_way_specialty')
    op.execute('DROP TYPE IF EXISTS flow_candidate_specialty')
    # ### end Alembic commands ###
