"""0001_init_app_arch

Revision ID: 1d329a1f11ea
Revises:
Create Date: 2026-03-13 09:03:07.889122

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d329a1f11ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'DRAFT',
                'AWAITING_CONFIRMATION',
                'CONFIRMED',
                'ARCHIVED',
                name='arch_task_status',
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tasks_slug'), 'tasks', ['slug'], unique=True)
    op.create_table(
        'templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'specialty',
            sa.Enum('BE', 'FE', 'QA', 'MOB', 'DEVOPS', name='arch_specialty'),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'DRAFT',
                'AWAITING_CONFIRMATION',
                'CONFIRMED',
                'ARCHIVED',
                name='arch_template_status',
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'REQUIREMENTS',
                'CALCULATION',
                'DATA_MODEL',
                'API',
                'HLD',
                'LLD',
                'RISKS',
                name='arch_section_type',
            ),
            nullable=False,
        ),
        sa.Column('score_scale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            'jsonb_array_length(score_scale) BETWEEN 1 AND 5',
            name='ck_sections_score_scale_length',
        ),
        sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_sections_template_id'), 'sections', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_template_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_table('templates')
    op.drop_index(op.f('ix_tasks_slug'), table_name='tasks')
    op.drop_table('tasks')
    # Удаляем enum-типы — они не удаляются автоматически
    op.execute('DROP TYPE IF EXISTS arch_task_status')
    op.execute('DROP TYPE IF EXISTS arch_specialty')
    op.execute('DROP TYPE IF EXISTS arch_template_status')
    op.execute('DROP TYPE IF EXISTS arch_section_type')
    # ### end Alembic commands ###
