"""0006_init_tech_app

Revision ID: 0ebd00ac782e
Revises: 9b2d3c99511a
Create Date: 2026-03-28 19:00:28.899092

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ebd00ac782e'
down_revision: Union[str, Sequence[str], None] = '9b2d3c99511a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tech_rooms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('candidate_token', sa.String(length=64), nullable=False),
        sa.Column('reviewer_token', sa.String(length=64), nullable=False),
        sa.Column(
            'status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='tech_room_status'), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tech_rooms_candidate_token'), 'tech_rooms', ['candidate_token'], unique=True)
    op.create_index(op.f('ix_tech_rooms_ended_at'), 'tech_rooms', ['ended_at'], unique=False)
    op.create_index(op.f('ix_tech_rooms_reviewer_token'), 'tech_rooms', ['reviewer_token'], unique=True)
    op.create_index(op.f('ix_tech_rooms_started_at'), 'tech_rooms', ['started_at'], unique=False)
    op.create_index(op.f('ix_tech_rooms_status'), 'tech_rooms', ['status'], unique=False)
    op.create_table(
        'tech_tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('specialty', sa.Enum('BE', 'FE', 'QA', 'MOB', 'DEVOPS', name='tech_task_specialty'), nullable=False),
        sa.Column('type', sa.Enum('THEORY', 'PRACTICE', name='tech_task_type'), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('score_scale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'status',
            sa.Enum('DRAFT', 'AWAITING_CONFIRMATION', 'CONFIRMED', 'ARCHIVED', name='tech_task_status'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tech_tasks_status'), 'tech_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tech_tasks_type'), 'tech_tasks', ['type'], unique=False)
    op.create_table(
        'tech_room_answers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('candidate_answer', sa.Text(), nullable=True),
        sa.Column('reviewer_comment', sa.Text(), nullable=True),
        sa.Column('score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['room_id'], ['tech_rooms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['tech_tasks.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('room_id', 'task_id', 'order', name='uq_room_answers_room_task_order'),
    )
    op.create_index(op.f('ix_tech_room_answers_room_id'), 'tech_room_answers', ['room_id'], unique=False)
    op.create_index(op.f('ix_tech_room_answers_task_id'), 'tech_room_answers', ['task_id'], unique=False)
    op.create_table(
        'tech_task_tags',
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['tech_tasks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('task_id', 'tag_id'),
    )
    op.create_table(
        'tech_room_tasks',
        sa.Column('room_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['room_id'], ['tech_rooms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['tech_tasks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('room_id', 'task_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_room_tasks')
    op.drop_table('tech_task_tags')
    op.drop_index(op.f('ix_tech_room_answers_task_id'), table_name='tech_room_answers')
    op.drop_index(op.f('ix_tech_room_answers_room_id'), table_name='tech_room_answers')
    op.drop_table('tech_room_answers')
    op.drop_index(op.f('ix_tech_tasks_type'), table_name='tech_tasks')
    op.drop_index(op.f('ix_tech_tasks_status'), table_name='tech_tasks')
    op.drop_table('tech_tasks')
    op.drop_index(op.f('ix_tech_rooms_status'), table_name='tech_rooms')
    op.drop_index(op.f('ix_tech_rooms_started_at'), table_name='tech_rooms')
    op.drop_index(op.f('ix_tech_rooms_reviewer_token'), table_name='tech_rooms')
    op.drop_index(op.f('ix_tech_rooms_ended_at'), table_name='tech_rooms')
    op.drop_index(op.f('ix_tech_rooms_candidate_token'), table_name='tech_rooms')
    op.drop_table('tech_rooms')
    # Удаляем enum-типы — они не удаляются автоматически
    op.execute('DROP TYPE IF EXISTS tech_task_status')
    op.execute('DROP TYPE IF EXISTS tech_task_specialty')
    op.execute('DROP TYPE IF EXISTS tech_task_type')
    op.execute('DROP TYPE IF EXISTS tech_room_status')
    # ### end Alembic commands ###
