"""

Revision ID: 6d59e482783e
Revises: 8d884983367d
Create Date: 2026-03-13 22:41:57.363541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d59e482783e'
down_revision: Union[str, Sequence[str], None] = '8d884983367d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rooms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('candidate_token', sa.String(length=64), nullable=False),
        sa.Column('reviewer_token', sa.String(length=64), nullable=False),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='room_status'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('candidate_token'),
        sa.UniqueConstraint('reviewer_token'),
    )
    op.create_index(op.f('ix_rooms_task_id'), 'rooms', ['task_id'], unique=False)
    op.create_index(op.f('ix_rooms_template_id'), 'rooms', ['template_id'], unique=False)
    op.create_table(
        'room_answers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Integer(), nullable=False),
        sa.Column('section_id', sa.Integer(), nullable=False),
        sa.Column('section_order', sa.Integer(), nullable=False),
        sa.Column('candidate_answer', sa.Text(), nullable=True),
        sa.Column('reviewer_comment', sa.Text(), nullable=True),
        sa.Column('mark', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_room_answers_room_id'), 'room_answers', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_answers_section_id'), 'room_answers', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_answers_section_id'), table_name='room_answers')
    op.drop_index(op.f('ix_room_answers_room_id'), table_name='room_answers')
    op.drop_table('room_answers')
    op.drop_index(op.f('ix_rooms_template_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_task_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
